"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { createConnectedSession, detectWallet, type ConnectedSession } from "../lib/midnight";
import { CONTRACT_ADDRESS, fetchLiveVerifications, type LiveVerification } from "../lib/contract";
import { ProofMark } from "./ProofMark";

const short = (value: string) => `${value.slice(0, 12)}…${value.slice(-10)}`;
const metric = ["Recycled content", "Carbon intensity", "Restricted chemical", "Renewable energy", "Responsible sourcing", "Certification", "ESG score"];

export function VerifyReceipt() {
  const [session, setSession] = useState<ConnectedSession | null>(null);
  const [records, setRecords] = useState<LiveVerification[]>([]);
  const [error, setError] = useState("");
  const connect = async () => { try { const wallet = await detectWallet(); if (!wallet) throw new Error("Connect 1AM to read the live preprod indexer."); const api = await wallet.connect("preprod"); setSession(await createConnectedSession(api, "/zk/verdeproof/")); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  useEffect(() => { if (session) fetchLiveVerifications(session.config.indexerUri).then(setRecords).catch(e => setError(e instanceof Error ? e.message : String(e))); }, [session]);
  return <main className="verify-page"><header className="verify-top"><Link href="/" className="site-logo"><span className="logo-glyph">V</span><span>Verde<span>Proof</span></span></Link><span className="network-label"><span className="pulse-dot" /> MIDNIGHT PREPROD</span></header><div className="receipt-wrap"><div className="receipt-kicker"><span>LIVE PUBLIC VERIFIER</span><span className="mono">{short(CONTRACT_ADDRESS)}</span></div><section className="receipt-card"><div className="receipt-status"><ProofMark /><div><span className="status-word">{records.length ? "VERIFIED" : "NO RECORDS"}</span><p>{records.length ? `${records.length} verification record${records.length === 1 ? "" : "s"} found on-chain.` : "No verification records have been written to this contract."}</p></div></div><div className="receipt-rule" /><div className="receipt-claim"><span>DEPLOYED CONTRACT</span><strong className="mono">{CONTRACT_ADDRESS}</strong><em>LIVE</em></div><div className="receipt-grid"><div><span>REQUIREMENTS</span><strong>Indexing live state</strong><small>Public ledger records only</small></div><div><span>VERIFICATIONS</span><strong>{records.length}</strong><small>Read from Midnight preprod</small></div><div><span>RAW MEASUREMENTS</span><strong>Hidden</strong><small>Never exposed by this viewer</small></div><div><span>STATUS</span><strong className="valid-text">On-chain</strong><small>Address pinned above</small></div></div>{records.length > 0 && <div className="activity-console">{records.map(record => <div className="audit-row" key={record.id}><span className="audit-check">✓</span><div><b>{record.result === 0 ? "Requirement passed" : "Disclosure recorded"}</b><small>{metric[record.metric] ?? "Compliance metric"} · {record.valueDisclosed || record.reportDisclosed ? "Selective detail disclosed" : "Raw value hidden"}</small></div><span className="mono">{short(record.id)}</span></div>)}</div>}<div className="private-callout"><span className="lock-symbol">▣</span><div><strong>Public state, private evidence.</strong><p>This page reads only the deployed contract’s public verification records. It does not invent receipts or reveal supplier measurements.</p></div></div>{!session && <button className="dark-button full-button" onClick={connect}>Connect 1AM to query live records →</button>}{error && <div className="deploy-error" role="alert">{error}</div>}</section><p className="receipt-footnote">Contract <span className="mono">{CONTRACT_ADDRESS}</span> · Midnight preprod · Indexer-backed</p></div></main>;
}
